### ISSUE TITLE
stop at selecting locations screen 

### ISSUE THREAD

**Issue by darkr4y** [mhf-ir/ubuntu-overssh-reinstallation#1]
On my vps's : Ubuntu 14.04 
On my local vm: Just load the ubuntu-overssh-reinstall.iso

when update-grub, it will restart and stop at selecting locations screen.
dont know why preseed install failed.

Updated:
maybe I know whats wrong ;)

**Comment by mhf-ir** [comment]
I dont test on ubuntu 14.04 but i dont think has any differences.
I hope you can find out what's the problem.

**Comment by darkr4y** [comment]
sorry for my mistake , I just upload the wrong preseed.conf ;)
so I closed this issue , thx for ur good project !
