### ISSUE TITLE
Support Kali Rolling NetInstall

### ISSUE THREAD

**Issue by darkr4y** [mhf-ir/ubuntu-overssh-reinstallation#2]
Kali Rolling based on Debian.
I modified this config:
https://github.com/offensive-security/kali-linux-preseed/blob/master/kali-linux-rolling-preseed.cfg

but when checking the mirror , it will wait for a long time and then show the bad archive mirror error.
Could you help me please ?

**Comment by mhf-ir** [comment]
Bad mirror error happened when the network is not configure properly. 
Check network configuration and try again.

**Comment by darkr4y** [comment]
Its very strange
I installed Ubuntu in the same vps as Kali Rolling
Could it be the problem about selecting network interface?

**Comment by mhf-ir** [comment]
Yeah check the default interface name on Kalli Rolling, 
For ubuntu default is https://github.com/mhf-ir/ubuntu-overssh-reinstallation#find-predictable-network-interface-names
So if the installation using `eth0` you must change in for installation.

Other network stuff must be check also.

**Comment by darkr4y** [comment]
I executed the above command on my ubunut vps.
it returned
```
udevadm test /sys/class/net/eth0 2>/dev/null | grep ID_NET_NAME_
ID_NET_NAME_MAC=enx00155de2e971
```
and I executed command on my local vmware which had kali rolling installed
it returned
```
ID_NET_NAME_MAC=enx000c299ee742
ID_NET_NAME_PATH=enp2s1
ID_NET_NAME_SLOT=ens33
```
so can I just use the interface on my local kali rolling replace to the remote on my vps?

**Comment by mhf-ir** [comment]
Predictable Network Interface depend on hardware and mac addr. so just you can use same name for the same installation. i donno about kalli convention but in ubuntu i tested, it's same on same device same hardware.
