### ISSUE TITLE
Choose SSH port

### ISSUE THREAD

**Issue by mishagale** [mhf-ir/ubuntu-overssh-reinstallation#3]
As far as I can see, there's no way to configure the SSH port that the install console will be served on - is it possible to add a configuration option to change this from the default port 22?

Or is there something that can be changed in the preseed file to accomplish this?

**Comment by mhf-ir** [comment]
You're right i also could not found for change `network-console` port i think better to ask debian/ubuntu maintainers for this one.
https://www.debian.org/releases/buster/example-preseed.txt

If you wanna change ssh port after installation you could use:

```
d-i preseed/late_command string \
  in-target sed -i '/Port/c\Port 22022' /etc/ssh/sshd_config ; 
```
